<?php
/**
 * @file
 * Code for the Ding Billetexpressen Import feature.
 */

include_once 'ding_billetexpressen_import.features.inc';
/**
 * @file
 * Module hooks are defined here.
 */
/**
 * Implements hook_menu().
 */
function ding_billetexpressen_import_menu() {
  $items = array();
  $items['admin/config/ding/billetexpressen'] = array(
    'title' => 'Billetexpressen import settings',
    'description' => 'Import events from Billetexpressen',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_billetexpressen_import_admin_form'),
    'file' => 'ding_billetexpressen_import.admin.inc',
  );
  $items['billetexpressen/library/%/delete/%ctools_js'] = array(
    'title' => 'Delete library from mapping',
    'description' => 'Delete callback for a mapped library',
    'page callback' => 'ding_billetexpressen_library_mapping_delete',
    'page arguments' => array(2, 4),
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_billetexpressen_import.admin.inc',
    'delivery callback' => 'ajax_deliver',
  );
  $items['billetexpressen/category/%/delete/%ctools_js'] = array(
    'title' => 'Delete category from mapping',
    'description' => 'Delete callback for a mapped category',
    'page callback' => 'ding_billetexpressen_category_mapping_delete',
    'page arguments' => array(2, 4),
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_billetexpressen_import.admin.inc',
    'delivery callback' => 'ajax_deliver',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ding_billetexpressen_import_theme($existing, $type, $theme, $path) {
  return array(
    'ding_billetexpressen_libraries_table' => array(
      'render element' => 'form',
      'file' => 'ding_billetexpressen_import.admin.inc',
    ),
    'ding_billetexpressen_categories_table' => array(
      'render element' => 'form',
      'file' => 'ding_billetexpressen_import.admin.inc',
    ),
  );
}

/**
 * Implements hook_feeds_presave().
 */
function ding_billetexpressen_import_feeds_presave(FeedsSource $source, $entity, $item) {
  // Map node category.
  $categories = variable_get('ding_billetexpressen_import_categories', array());
  foreach ($categories as $category) {
    if (!empty($item['category'])) {
      if ($category['mapping'] == $item['category']) {
        $entity->field_ding_event_category[LANGUAGE_NONE][0]['tid'] = $category['category'];
      }
    }
  }

  // Map node library.
  $libraries = variable_get('ding_billetexpressen_import_libraries', array());
  foreach ($libraries as $library) {
    if ($library['mapping'] == $item['library']) {
      $entity->og_group_ref[LANGUAGE_NONE][0]['target_id'] = $library['library'];
    }
  }

  // Map node status only for new nodes.
  if (!$entity->nid) {
    $status = variable_get('ding_billetexpressen_import_status', 0);
    $entity->status = $status;
  }

  // Convert date to UTC.
  $date_start = new DateTime($item['date_start']);
  $date_start->setTimezone(new DateTimeZone('UTC'));
  $value = $date_start->format('Y:m:d H:i:s');
  $entity->field_ding_event_date[LANGUAGE_NONE][0]['value'] = $value;

  $date_end = new DateTime($item['date_end']);
  $date_end->setTimezone(new DateTimeZone('UTC'));
  $value = $date_end->format('Y:m:d H:i:s');
  $entity->field_ding_event_date[LANGUAGE_NONE][0]['value2'] = $value;

  // Make sure ticket price is numeric.
  if (isset($item['ticket_price'])) {
    $entity->field_ding_event_price[LANGUAGE_NONE][0]['value'] = (int) $item['ticket_price'];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add default value to the import page.
 */
function ding_billetexpressen_import_form_feeds_import_form_alter(&$form, &$form_state, $form_id) {
  $args = arg();
  if ($args[0] == 'import' && $args[1] == 'billetexpressen_events') {
    $form['feeds']['FeedsHTTPFetcher']['source']['#default_value'] = variable_get('ding_billetexpressen_import_url', '');
    $form['#attached'] = array(
        'css' => array(
          drupal_get_path('module', 'ding_billetexpressen_import') . '/css/ding_billetexpressen_import.css'
        ),
      );
  }
}
